In [4]:
import pandas as pd

# Load your dataset
df = pd.read_csv("Mental Health Dataset.csv")

# Display the first few rows
df.head()

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
0,8/27/2014 11:29,Female,United States,Corporate,NaN,No,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Not sure
1,8/27/2014 11:31,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,No
2,8/27/2014 11:32,Female,United States,Corporate,NaN,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes
3,8/27/2014 11:37,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,Maybe,Yes
4,8/27/2014 11:43,Female,United States,Corporate,No,Yes,Yes,1-14 days,Yes,No,Yes,Medium,No,No,Yes,No,Yes

In [17]:
# Check total missing values per column
df.isnull().sum()

Timestamp                     0
Gender                        0
Country                       0
Occupation                    0
self_employed              5202
family_history                0
treatment                     0
Days_Indoors                  0
Growing_Stress                0
Changes_Habits                0
Mental_Health_History         0
Mood_Swings                   0
Coping_Struggles              0
Work_Interest                 0
Social_Weakness               0
mental_health_interview       0
care_options                  0
dtype: int64

In [19]:
import pandas as pd

# Replace 'your_file.csv' with your actual file name
df = pd.read_csv('Mental Health Dataset.csv')

# Now you can check for missing values
df.isnull().sum()

Timestamp                     0
Gender                        0
Country                       0
Occupation                    0
self_employed              5202
family_history                0
treatment                     0
Days_Indoors                  0
Growing_Stress                0
Changes_Habits                0
Mental_Health_History         0
Mood_Swings                   0
Coping_Struggles              0
Work_Interest                 0
Social_Weakness               0
mental_health_interview       0
care_options                  0
dtype: int64

In [20]:
# Remove all rows that contain at least one null value
df = df.dropna()

In [6]:
df.isnull().sum()

Timestamp                  0
Gender                     0
Country                    0
Occupation                 0
self_employed              0
family_history             0
treatment                  0
Days_Indoors               0
Growing_Stress             0
Changes_Habits             0
Mental_Health_History      0
Mood_Swings                0
Coping_Struggles           0
Work_Interest              0
Social_Weakness            0
mental_health_interview    0
care_options               0
dtype: int64

In [9]:
df = df.drop_duplicates()

In [10]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.tail(10)

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
292354,4/2/2015 15:47,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292355,4/11/2015 14:35,Male,Poland,Business,Yes,No,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,No
292356,4/23/2015 14:03,Male,Ireland,Business,No,No,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,No
292357,5/6/2015 10:14,Male,Australia,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292358,5/6/2015 16:55,Male,United States,Business,No,No,No,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,Maybe,Not sure
292359,7/27/2015 23:25,Male,United States,Business,Yes,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,Maybe,Not sure
292360,8/17/2015 9:38,Male,South Africa,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292361,8/25/2015 19:59,Male,United States,Business,No,Yes,No,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,No
292362,9/26/2015 1:07,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes
292363,2/1/2016 23:04,Male,United States,Business,No,Yes,Yes,15-30 days,No,Maybe,No,Low,Yes,No,Maybe,No,Yes

In [9]:
df[(df['Growing_Stress'] == "Yes") & (df['Occupation'] == "Business")]

,Timestamp,Gender,Country,Occupation,self_employed,family_history,treatment,Days_Indoors,Growing_Stress,Changes_Habits,Mental_Health_History,Mood_Swings,Coping_Struggles,Work_Interest,Social_Weakness,mental_health_interview,care_options
363,8/27/2014 11:29,Female,United States,Business,NaN,No,Yes,Go out Every day,Yes,Maybe,No,Low,No,Maybe,Maybe,No,Not sure
364,8/27/2014 11:31,Female,United States,Business,NaN,Yes,Yes,Go out Every day,Yes,Maybe,No,Low,No,Maybe,Maybe,No,No
365,8/27/2014 11:32,Female,United States,Business,NaN,Yes,Yes,Go out Every day,Yes,Maybe,No,Low,No,Maybe,Maybe,No,Yes
366,8/27/2014 11:37,Female,United States,Business,No,Yes,Yes,Go out Every day,Yes,Maybe,No,Low,No,Maybe,Maybe,Maybe,Yes
367,8/27/2014 11:43,Female,United States,Business,No,Yes,Yes,Go out Every day,Yes,Maybe,No,Low,No,Maybe,Maybe,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286209,7/27/2015 23:25,Male,United States,Business,Yes,Yes,Yes,15-30 days,Yes,Maybe,Yes,High,No,No,No,Maybe,Not sure
286210,8/17/2015 9:38,Male,South Africa,Business,No,Yes,Yes,15-30 days,Yes,Maybe,Yes,High,No,No,No,No,Yes
286211,8/25/2015 19:59,Male,United States,Business,No,Yes,No,15-30 days,Yes,Maybe,Yes,High,No,No,No,No,No
286212,9/26/2015 1:07,Male,United States,Business,No,Yes,Yes,15-30 days,Yes,Maybe,Yes,High,No,No,No,No,Yes
286213,2/1/2016 23:04,Male,United States,Business,No,Yes,Yes,15-30 days,Yes,Maybe,Yes,High,No,No,No,No,Yes

In [12]:
filtered_df = df[
    (df["self_employed"] == "No") &
    (df["Occupation"] == "Business") &
    (df["Gender"] == "Female") &
    (df["Work_Interest"].isin(["Maybe"])) &
    (df["Changes_Habits"].isin(["No", "Maybe", "Yes"]))
]
print(filtered_df.isnull().sum())

Timestamp                  0
Gender                     0
Country                    0
Occupation                 0
self_employed              0
family_history             0
treatment                  0
Days_Indoors               0
Growing_Stress             0
Changes_Habits             0
Mental_Health_History      0
Mood_Swings                0
Coping_Struggles           0
Work_Interest              0
Social_Weakness            0
mental_health_interview    0
care_options               0
dtype: int64